FROM golang:latest
MAINTAINER Anup Chenthamarakshan <anupc@dropbox.com>

RUN go get -v github.com/go-martini/martini gopkg.in/amz.v1/s3 gopkg.in/gorp.v1 github.com/lib/pq github.com/martini-contrib/render github.com/stretchr/testify golang.org/x/tools/cmd/cover github.com/cenkalti/backoff
