// generated by stringer -type=ArtifactState; DO NOT EDIT

package model

import "fmt"

const _ArtifactState_name = "UNKNOWN_ARTIFACT_STATEERRORAPPENDINGAPPEND_COMPLETEWAITING_FOR_UPLOADUPLOADINGUPLOADEDDEADLINE_EXCEEDEDCLOSED_WITHOUT_DATA"

var _ArtifactState_index = [...]uint8{0, 22, 27, 36, 51, 69, 78, 86, 103, 122}

func (i ArtifactState) String() string {
	if i >= ArtifactState(len(_ArtifactState_index)-1) {
		return fmt.Sprintf("ArtifactState(%d)", i)
	}
	return _ArtifactState_name[_ArtifactState_index[i]:_ArtifactState_index[i+1]]
}
