// generated by stringer -type=BucketState; DO NOT EDIT

package model

import "fmt"

const _BucketState_name = "UNKNOWNOPENCLOSEDTIMEDOUT"

var _BucketState_index = [...]uint8{0, 7, 11, 17, 25}

func (i BucketState) String() string {
	if i >= BucketState(len(_BucketState_index)-1) {
		return fmt.Sprintf("BucketState(%d)", i)
	}
	return _BucketState_name[_BucketState_index[i]:_BucketState_index[i+1]]
}
