// Code generated by go-bindata.
// sources:
// migrations/1_initial.sql
// migrations/2_index_artifactid_size.sql
// migrations/README
// DO NOT EDIT!

package database

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"strings"
	"os"
	"time"
	"io/ioutil"
	"path/filepath"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _migrations1_initialSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x94\x92\x41\x73\xba\x30\x10\xc5\xef\x7c\x8a\x1d\x2e\xea\xfc\xf5\xf4\x3f\x7a\xc2\x9a\xb6\x99\x22\x2a\x84\xa9\xf6\x16\xc3\xaa\x19\x31\x30\x10\xc6\xb6\x9f\xbe\x09\x88\xd2\xce\xb4\xb6\xc7\xf7\xf2\xd8\xfd\xed\xb2\xa3\x11\xfc\x3b\xca\x5d\xc1\x35\x42\x9c\x3b\x46\x46\x4b\x1f\xa4\x82\x12\x85\x96\x99\x82\x5e\x9c\xf7\x40\x96\x80\xaf\x28\x2a\x8d\x09\x9c\xf6\xa8\x40\xef\x8d\xd5\x7c\x67\x43\x46\xf0\x3c\x4f\x25\x26\xce\x5d\x48\x3c\x46\x80\x79\x13\x9f\x00\xbd\x87\x60\xce\x80\xac\x68\xc4\x22\xd8\x54\xe2\x80\x1a\xfa\x0e\x40\x62\xfa\x89\x34\x2b\x4d\x3d\x46\x67\x24\x62\xde\x6c\x01\xcf\x94\x3d\xd6\x12\x5e\xe6\x01\x19\xb6\xb1\x02\xb9\xbe\x91\x93\xe6\x99\xac\x58\xdd\x2c\x88\x7d\x1f\x16\x21\x9d\x79\xe1\x1a\x9e\xc8\xda\xbe\x67\x27\x85\x45\x1d\xb1\xaa\xd4\x76\x5a\xab\x9c\xc1\xf8\x27\x60\x5e\x68\xb9\xe5\xa2\x41\x6e\xe8\xcf\x9d\xfe\x08\x37\xa1\x0f\x11\x09\xa9\xe7\x7f\x4b\xa8\xf8\x11\xaf\x80\xff\xab\x22\xbd\x2a\xf9\x8e\xb6\x02\x0d\xbe\xd0\xd7\x10\xc8\x93\x54\x2a\x3c\x4a\x55\x5e\xcc\x38\xa0\xcb\x98\x40\xbf\x45\x1e\xd6\xe5\x07\x37\xa6\x4d\xb3\x9d\xd8\x57\xea\x00\x7d\x57\x26\xee\x0d\x66\x18\x82\xdb\xae\xe7\x9c\xb6\x7c\xe0\x6e\xde\x34\x66\xdb\x6d\x89\xba\x63\xda\x11\x3a\x52\x64\x4a\xa3\x32\x01\x0b\x6c\xa0\x9c\xee\x15\x4e\xcd\xcf\x6a\xef\xf0\x72\x84\xd6\xfc\xd5\x19\x16\x59\x9a\x9a\xd7\x0d\x17\x07\x67\x1a\xce\x17\xe7\x49\x9b\x4d\x8c\xbb\x56\x4b\xff\xc9\x6c\x77\x30\x76\x3e\x02\x00\x00\xff\xff\x08\x1b\xf1\xb5\x19\x03\x00\x00")

func migrations1_initialSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations1_initialSql,
		"migrations/1_initial.sql",
	)
}

func migrations1_initialSql() (*asset, error) {
	bytes, err := migrations1_initialSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/1_initial.sql", size: 793, mode: os.FileMode(420), modTime: time.Unix(1439319605, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _migrations2_index_artifactid_sizeSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xd2\xd5\x55\xd0\xce\xcd\x4c\x2f\x4a\x2c\x49\x55\x08\x2d\xe0\x72\x0e\x72\x75\x0c\x71\x55\xf0\xf4\x73\x71\x8d\x50\xc8\xc9\x4f\x4f\xce\x28\xcd\xcb\x8e\x4f\x2c\x2a\xc9\x4c\x4b\x4c\x2e\xc9\x4c\x89\x2f\xce\xac\x4a\x8d\xcf\x49\x2c\x2e\x51\xf0\xf7\x83\x2b\x50\xd0\x40\xa8\xd0\x51\x00\x29\x51\x70\x71\x0d\x76\x56\xf0\x0b\xf5\xf1\x09\x56\xf0\x71\x0c\x0e\xd1\xb4\xe6\xe2\x42\xb6\xca\x25\xbf\x3c\x8f\xcb\x25\xc8\x3f\x80\x18\xab\xac\xb9\x00\x01\x00\x00\xff\xff\x72\xaa\x21\x25\xa6\x00\x00\x00")

func migrations2_index_artifactid_sizeSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations2_index_artifactid_sizeSql,
		"migrations/2_index_artifactid_size.sql",
	)
}

func migrations2_index_artifactid_sizeSql() (*asset, error) {
	bytes, err := migrations2_index_artifactid_sizeSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/2_index_artifactid_size.sql", size: 166, mode: os.FileMode(420), modTime: time.Unix(1439319605, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _migrationsReadme = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x84\x91\xcf\x6a\xe3\x30\x10\x87\xef\x7a\x8a\x81\xbd\xec\x86\x8d\x7c\x0f\x69\x20\xd0\x1e\xfb\x07\x52\xe8\x31\x91\xad\xb1\x2c\x2a\x4b\x8e\x66\x9c\x34\x6f\xdf\x91\xd3\x04\x9a\x1e\x6a\xf0\x41\x68\x34\xdf\x37\xf3\x5b\x67\xf6\xad\x69\x98\x60\xc3\x29\x23\xdc\x1b\x36\xb5\x21\x84\x47\xef\xb2\x61\x9f\x22\xa9\xbb\xdf\x3f\xa5\xd6\xd6\x82\x89\x27\xe8\x2f\xef\x80\x9a\xec\x07\x69\xcc\x9e\x03\x5a\x58\x12\xee\xb7\x31\xad\xb6\x4b\xea\x52\xe6\x6d\x8f\x44\xc6\xe1\x4a\xd3\x3e\x00\x27\xe0\xce\x13\xb4\x29\x58\xcc\x1a\x36\x5f\x6f\x8f\x3e\x04\xa8\x51\xe1\x07\x36\x23\x4b\x17\x1f\xaf\x8d\x20\xe5\xa9\xf6\x25\x60\x11\x26\x44\xe8\x98\x07\x5a\x54\x95\xf3\xdc\x8d\xb5\x6e\x52\x5f\xe5\xb1\xc6\x78\xa8\x04\x32\x3f\xab\xe1\x9f\x63\xf6\xec\xa3\x9b\x5f\x55\x0b\x37\x2b\x37\x7a\x8b\xc1\x47\x24\x10\xfb\x2e\x1d\x8b\x55\xa9\x45\x71\xc3\x9f\x83\x69\xa5\x9e\x9e\x5f\x1f\x16\x17\x81\x3c\x46\xd8\xb9\x04\x0e\x23\x16\x0e\xcc\x0f\xa0\x2b\xad\xf5\x0e\x4c\xcb\x98\xa1\x37\xef\x82\x9d\xb6\xd4\x74\x26\x3a\x01\xdd\xce\xfd\x86\x60\x24\x05\xec\x6b\xb4\xb6\x14\x0b\x59\xdd\x92\xc1\x10\x18\x10\x52\xeb\x03\xc2\xdf\xa9\x01\x67\x13\x29\x9c\xab\xe4\x38\x60\x96\x91\x7a\x59\x58\x7d\xfa\x26\xb5\xfb\x27\x10\xd9\x4e\x1a\xb9\x08\xc7\xc2\x90\x7b\x75\xbd\xff\x7f\x33\xec\xc4\x98\x62\x98\xc9\xb4\x33\x09\x43\x32\x68\xc2\x68\xb1\xe4\x2d\xff\x30\x04\x8f\x56\xab\xcf\x00\x00\x00\xff\xff\x09\x4a\x3a\x3d\x4a\x02\x00\x00")

func migrationsReadmeBytes() ([]byte, error) {
	return bindataRead(
		_migrationsReadme,
		"migrations/README",
	)
}

func migrationsReadme() (*asset, error) {
	bytes, err := migrationsReadmeBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/README", size: 586, mode: os.FileMode(420), modTime: time.Unix(1439319605, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"migrations/1_initial.sql": migrations1_initialSql,
	"migrations/2_index_artifactid_size.sql": migrations2_index_artifactid_sizeSql,
	"migrations/README": migrationsReadme,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"migrations": &bintree{nil, map[string]*bintree{
		"1_initial.sql": &bintree{migrations1_initialSql, map[string]*bintree{
		}},
		"2_index_artifactid_size.sql": &bintree{migrations2_index_artifactid_sizeSql, map[string]*bintree{
		}},
		"README": &bintree{migrationsReadme, map[string]*bintree{
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

